---
platform: ppc64le

image_resource:
  type: docker-image
  source:
    repository: 140.211.168.31:5000/golang1.6
    insecure_registries: ["140.211.168.31:5000"]

inputs:
- name: semver-resource
  path: gopath/src/github.com/concourse/semver-resource

outputs:
- name: built-resource

params:
  SEMVER_TESTING_ACCESS_KEY_ID:
  SEMVER_TESTING_SECRET_ACCESS_KEY:
  SEMVER_TESTING_BUCKET:
  SEMVER_TESTING_REGION:

run:
  path: gopath/src/github.com/concourse/semver-resource/scripts/ci
