#!/bin/bash

mkdir -p assets
GOOS=linux GOARCH=ppc64le go build -o assets/in in/main.go
GOOS=linux GOARCH=ppc64le go build -o assets/out out/main.go
GOOS=linux GOARCH=ppc64le go build -o assets/check check/main.go
